### ISSUE TITLE
Color coding to show whether “latest version” is better or worse

### ISSUE THREAD

**Issue by rkothari19** [mozilla/missioncontrol#213] opened 2018-02-06 00:08 UTC
Color coding to show whether “latest version” is better or worse than “previous version (avg)” https://data-missioncontrol.dev.mozaws.net/#/release/windows

**Comment by wlach** [comment] 2018-02-07 15:31
We have to be careful about this, as a change in the median sample for any particular measure might not indicate a regression (since there are so many causes of natural variation for these numbers). But yes, for unambiguous cases we should do this (or something like it).

**Comment by wlach** [comment] 2018-02-07 15:36
@mreid suggests maybe looking at cerberus for inspiration on how to detect that there is a significant, sustained change.

**Comment by wlach** [comment] 2018-03-22 00:56
Right now we use color coding on the text in the main page to show significant (> 25% changes) in the mean for any particular measure relative to the previous release. I'm pretty happy with the way this turned out -- it gives a hint on things to look at without blazing alarm bells.

![image](https://user-images.githubusercontent.com/20569/37745264-476c83da-2d4a-11e8-982e-98cb86d3d332.png)

I'm going to close this for now. We may well want to tweak this further but I think we can open a new issues for that.

**Closed by wlach** 2018-03-22 00:56 UTC
Labels: frontend
